kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: m2-storage-class
  namespace: perf-platform
provisioner: kubernetes.io/azure-file
mountOptions:
  - nolock
reclaimPolicy: Retain

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: helm-storage-class
  namespace: perf-platform
provisioner: kubernetes.io/azure-file
mountOptions:
  - nolock
reclaimPolicy: Retain