apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m2-pvc
  namespace: perf-platform
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: m2-storage-class
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-pvc
  namespace: perf-platform
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: helm-storage-class
  resources:
    requests:
      storage: 1Gi