---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi