namespace: monitoring
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  path: /grafana/?(.*)
  backend:
    service:
      name: grafana
      port:
        number: 3000
  

grafana.ini:
  server:
    root_url: http://localhost/grafana # this host can be localhost