# Persistent Volume Claim for Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-db-pv-claim
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
